# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import greeter_pb2 as greeter__pb2


class DocumentFinderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.FindDoucments = channel.unary_stream(
                '/greeter.DocumentFinder/FindDoucments',
                request_serializer=greeter__pb2.FindDocumentsRequest.SerializeToString,
                response_deserializer=greeter__pb2.DocumentResponse.FromString,
                )


class DocumentFinderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def FindDoucments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DocumentFinderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'FindDoucments': grpc.unary_stream_rpc_method_handler(
                    servicer.FindDoucments,
                    request_deserializer=greeter__pb2.FindDocumentsRequest.FromString,
                    response_serializer=greeter__pb2.DocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'greeter.DocumentFinder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DocumentFinder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def FindDoucments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/greeter.DocumentFinder/FindDoucments',
            greeter__pb2.FindDocumentsRequest.SerializeToString,
            greeter__pb2.DocumentResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
