// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PublicHistoryService.Infrastructure.EntityFramework.Contexts;

#nullable disable

namespace PublicHistoryService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20240709160825_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public-history-service")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.CommentedArticleReadModel", b =>
                {
                    b.Property<Guid>("CommentedArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CommentedArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("CommentedArticle", "public-history-service");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.SearchedArticleDataReadModel", b =>
                {
                    b.Property<Guid>("SearchedArticleDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchedData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SearchedArticleDataId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchedArticleData", "public-history-service");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.SearchedTopicDataReadModel", b =>
                {
                    b.Property<Guid>("SearchedTopicDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SearchedData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("SearchedTopicDataId");

                    b.HasIndex("UserId");

                    b.ToTable("SearchedTopicData", "public-history-service");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.UserReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("User", "public-history-service");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.ViewedArticleReadModel", b =>
                {
                    b.Property<Guid>("ViewedArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ViewedArticleId");

                    b.HasIndex("UserId");

                    b.ToTable("ViewedArticle", "public-history-service");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.ViewedUserReadModel", b =>
                {
                    b.Property<Guid>("ViewedUserReadModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViewedUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ViewerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ViewedUserReadModelId");

                    b.HasIndex("ViewerUserId");

                    b.ToTable("ViewedUser", "public-history-service");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.CommentedArticleReadModel", b =>
                {
                    b.HasOne("PublicHistoryService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("CommentedArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_CommentedArticles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.SearchedArticleDataReadModel", b =>
                {
                    b.HasOne("PublicHistoryService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("SearchedArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_SearchedArticles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.SearchedTopicDataReadModel", b =>
                {
                    b.HasOne("PublicHistoryService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("SearchedTopics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_SearchedTopics");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.ViewedArticleReadModel", b =>
                {
                    b.HasOne("PublicHistoryService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ViewedArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_ViewedArticles");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.ViewedUserReadModel", b =>
                {
                    b.HasOne("PublicHistoryService.Infrastructure.EntityFramework.Models.UserReadModel", "ViewedUser")
                        .WithMany("ViewedUsers")
                        .HasForeignKey("ViewerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_ViewedUsers");

                    b.Navigation("ViewedUser");
                });

            modelBuilder.Entity("PublicHistoryService.Infrastructure.EntityFramework.Models.UserReadModel", b =>
                {
                    b.Navigation("CommentedArticles");

                    b.Navigation("SearchedArticles");

                    b.Navigation("SearchedTopics");

                    b.Navigation("ViewedArticles");

                    b.Navigation("ViewedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
