// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TopicArticleService.Infrastructure.EntityFramework.Contexts;

#nullable disable

namespace TopicArticleService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20240409120648_InitialRead")]
    partial class InitialRead
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("topic-article-service")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentDislikeReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleCommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleCommentDislike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentLikeReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleCommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleCommentLike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ArticleCommentId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentArticleCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleComment", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleDislikeReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleDislike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleLikeReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleLike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrevTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublishingDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId");

                    b.HasIndex("TopicId");

                    b.ToTable("Article", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.Property<Guid>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("TopicId");

                    b.HasIndex("ParentTopicId");

                    b.ToTable("Topic", "topic-article-service");

                    b.HasData(
                        new
                        {
                            TopicId = new Guid("44aaeb3f-cae7-4a8c-93a6-2b13deddd3bd"),
                            TopicName = "Cybersecurity",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("51f85e58-0de3-4b03-9876-d3ce0c3abcf6"),
                            TopicName = "Programming",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("5ae9a3dc-d76c-4b4d-8a1f-a17fe5c817eb"),
                            ParentTopicId = new Guid("44aaeb3f-cae7-4a8c-93a6-2b13deddd3bd"),
                            TopicName = "News",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("2670e81a-8bd7-423a-acd4-5892660934d8"),
                            ParentTopicId = new Guid("44aaeb3f-cae7-4a8c-93a6-2b13deddd3bd"),
                            TopicName = "Projects",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("45f672df-8bdb-456c-8ea1-dd5b0b867df7"),
                            ParentTopicId = new Guid("44aaeb3f-cae7-4a8c-93a6-2b13deddd3bd"),
                            TopicName = "Laws",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("4204c27a-aed5-459e-a245-58978895875f"),
                            ParentTopicId = new Guid("44aaeb3f-cae7-4a8c-93a6-2b13deddd3bd"),
                            TopicName = "Law regulations",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("edd8a756-6238-45cf-9275-4037af21b388"),
                            ParentTopicId = new Guid("51f85e58-0de3-4b03-9876-d3ce0c3abcf6"),
                            TopicName = "News",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("c9523aef-2faa-4e89-8599-43b3089b5960"),
                            ParentTopicId = new Guid("51f85e58-0de3-4b03-9876-d3ce0c3abcf6"),
                            TopicName = "Projects",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("76681b14-e42a-47c7-b19f-954cba4c5dd9"),
                            ParentTopicId = new Guid("5ae9a3dc-d76c-4b4d-8a1f-a17fe5c817eb"),
                            TopicName = "America",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("80dfc5a1-7813-456d-a7b2-4b8e93e81f16"),
                            ParentTopicId = new Guid("5ae9a3dc-d76c-4b4d-8a1f-a17fe5c817eb"),
                            TopicName = "Asia",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("888a5c96-7c7c-4f98-90b6-91a0c2d401b0"),
                            ParentTopicId = new Guid("5ae9a3dc-d76c-4b4d-8a1f-a17fe5c817eb"),
                            TopicName = "Europe",
                            Version = 0
                        });
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("User", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserArticleReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("UserArticle", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserTopicReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SubscriptionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("UserTopic", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentDislikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "ArticleComment")
                        .WithMany("ArticleCommentDislikes")
                        .HasForeignKey("ArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleComment_ArticleCommentDislikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.User", "User")
                        .WithMany("ArticleCommentDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleCommentDislikes");

                    b.Navigation("ArticleComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentLikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "ArticleComment")
                        .WithMany("ArticleCommentLikes")
                        .HasForeignKey("ArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleComment_ArticleCommentLikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.User", "User")
                        .WithMany("ArticleCommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleCommentLikes");

                    b.Navigation("ArticleComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleComments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Article_ArticleComments");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ParentArticleComment_ChildArticleComments");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.User", "User")
                        .WithMany("ArticleComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_User_ArticleComments");

                    b.Navigation("Article");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleDislikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleDislikes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_ArticleDislikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.User", "User")
                        .WithMany("ArticleDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleDislikes");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleLikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_ArticleLikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.User", "User")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleLikes");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Topic")
                        .WithMany("Articles")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Articles");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ParentTopic_ChildTopics");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserArticleReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("UserArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_UserArticles");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.User", "User")
                        .WithMany("UserArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_UserArticles");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserTopicReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Topic")
                        .WithMany("Users")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Users");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.User", "User")
                        .WithMany("Topics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_Topics");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.Navigation("ArticleCommentDislikes");

                    b.Navigation("ArticleCommentLikes");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleDislikes");

                    b.Navigation("ArticleLikes");

                    b.Navigation("UserArticles");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.User", b =>
                {
                    b.Navigation("ArticleCommentDislikes");

                    b.Navigation("ArticleCommentLikes");

                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleDislikes");

                    b.Navigation("ArticleLikes");

                    b.Navigation("Topics");

                    b.Navigation("UserArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
