// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TopicArticleService.Infrastructure.EntityFramework.Contexts;

#nullable disable

namespace TopicArticleService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20240502054159_Added TopicFullName property in the Topic model")]
    partial class AddedTopicFullNamepropertyintheTopicmodel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("topic-article-service")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentDislikeReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleCommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleCommentDislike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentLikeReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleCommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleCommentLike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ParentArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ArticleCommentId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentArticleCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleComment", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleDislikeReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleDislike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleLikeReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleLike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrevTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublishingDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId");

                    b.HasIndex("TopicId");

                    b.ToTable("Article", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.Property<Guid>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("TopicId");

                    b.HasIndex("ParentTopicId");

                    b.ToTable("Topic", "topic-article-service");

                    b.HasData(
                        new
                        {
                            TopicId = new Guid("7a954d4e-2483-433a-ac1a-dc1c5108daed"),
                            TopicFullName = "cybersecurity",
                            TopicName = "Cybersecurity",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("17c50c00-2c7e-44c6-a490-e576eb9da3f6"),
                            TopicFullName = "programming",
                            TopicName = "Programming",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("f25a86ca-37d9-41c0-b01a-03303dfed27d"),
                            ParentTopicId = new Guid("7a954d4e-2483-433a-ac1a-dc1c5108daed"),
                            TopicFullName = "cybersecurity_news",
                            TopicName = "News",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("2db7c75c-3eea-4c91-ad84-69c5b0fad176"),
                            ParentTopicId = new Guid("7a954d4e-2483-433a-ac1a-dc1c5108daed"),
                            TopicFullName = "cybersecurity_projects",
                            TopicName = "Projects",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("708707f4-50b8-4f43-8da5-3f07d6644e59"),
                            ParentTopicId = new Guid("7a954d4e-2483-433a-ac1a-dc1c5108daed"),
                            TopicFullName = "cybersecurity_laws",
                            TopicName = "Laws",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("8032b797-723d-4019-abc9-b5b8aa7c0cb9"),
                            ParentTopicId = new Guid("7a954d4e-2483-433a-ac1a-dc1c5108daed"),
                            TopicFullName = "cybersecurity_law_regulations",
                            TopicName = "Law regulations",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("9194c4f2-7789-4995-9f92-ca5bb997cf73"),
                            ParentTopicId = new Guid("17c50c00-2c7e-44c6-a490-e576eb9da3f6"),
                            TopicFullName = "programming_news",
                            TopicName = "News",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("e1712972-5d22-4bc5-be12-4bdb9de44386"),
                            ParentTopicId = new Guid("17c50c00-2c7e-44c6-a490-e576eb9da3f6"),
                            TopicFullName = "programming_projects",
                            TopicName = "Projects",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("0993403f-51c3-4d05-863c-e745845f8050"),
                            ParentTopicId = new Guid("f25a86ca-37d9-41c0-b01a-03303dfed27d"),
                            TopicFullName = "cybersecurity_news_america",
                            TopicName = "America",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("480fb040-2768-47d2-a065-30a7deaedf6a"),
                            ParentTopicId = new Guid("f25a86ca-37d9-41c0-b01a-03303dfed27d"),
                            TopicFullName = "cybersecurity_news_asia",
                            TopicName = "Asia",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("e983ed0d-20e2-43fb-b5bd-559bc6262906"),
                            ParentTopicId = new Guid("f25a86ca-37d9-41c0-b01a-03303dfed27d"),
                            TopicFullName = "cybersecurity_news_europe",
                            TopicName = "Europe",
                            Version = 0
                        });
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserArticleReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("UserArticle", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("User", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserTopicReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SubscriptionTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("UserTopic", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentDislikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "ArticleComment")
                        .WithMany("ArticleCommentDislikes")
                        .HasForeignKey("ArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleComment_ArticleCommentDislikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleCommentDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleCommentDislikes");

                    b.Navigation("ArticleComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentLikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "ArticleComment")
                        .WithMany("ArticleCommentLikes")
                        .HasForeignKey("ArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleComment_ArticleCommentLikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleCommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleCommentLikes");

                    b.Navigation("ArticleComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleComments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Article_ArticleComments");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ParentArticleComment_ChildArticleComments");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_User_ArticleComments");

                    b.Navigation("Article");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleDislikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleDislikes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_ArticleDislikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleDislikes");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleLikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_ArticleLikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleLikes");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Topic")
                        .WithMany("Articles")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Articles");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ParentTopic_ChildTopics");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserArticleReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("UserArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_UserArticles");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("UserArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_UserArticles");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserTopicReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Topic")
                        .WithMany("Users")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Users");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("Topics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_Topics");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.Navigation("ArticleCommentDislikes");

                    b.Navigation("ArticleCommentLikes");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleDislikes");

                    b.Navigation("ArticleLikes");

                    b.Navigation("UserArticles");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", b =>
                {
                    b.Navigation("ArticleCommentDislikes");

                    b.Navigation("ArticleCommentLikes");

                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleDislikes");

                    b.Navigation("ArticleLikes");

                    b.Navigation("Topics");

                    b.Navigation("UserArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
