// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TopicArticleService.Infrastructure.EntityFramework.Contexts;

#nullable disable

namespace TopicArticleService.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ReadDbContext))]
    [Migration("20240627121123_Second migration")]
    partial class Secondmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("topic-article-service")
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentDislikeReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArticleCommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleCommentDislike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentLikeReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArticleCommentId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleCommentLike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.Property<Guid>("ArticleCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentArticleCommentId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ArticleCommentId");

                    b.HasIndex("ArticleId");

                    b.HasIndex("ParentArticleCommentId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleComment", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleDislikeReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleDislike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleLikeReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArticleId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ArticleLike", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Link")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrevTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublishingDate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ArticleId");

                    b.HasIndex("TopicId");

                    b.ToTable("Article", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.Property<Guid>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ParentTopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("TopicFullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("TopicId");

                    b.HasIndex("ParentTopicId");

                    b.ToTable("Topic", "topic-article-service");

                    b.HasData(
                        new
                        {
                            TopicId = new Guid("262f36ed-c72b-4ca3-a959-acefc2bcd524"),
                            TopicFullName = "cybersecurity",
                            TopicName = "Cybersecurity",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("d98ad359-1bd9-4a67-878b-cd45ee6c59c9"),
                            TopicFullName = "programming",
                            TopicName = "Programming",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("ccc0167e-0b76-46a7-a368-46a66da72399"),
                            ParentTopicId = new Guid("262f36ed-c72b-4ca3-a959-acefc2bcd524"),
                            TopicFullName = "cybersecurity_news",
                            TopicName = "News",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("eb5bd072-579f-4be7-a88c-2833e113ee04"),
                            ParentTopicId = new Guid("262f36ed-c72b-4ca3-a959-acefc2bcd524"),
                            TopicFullName = "cybersecurity_projects",
                            TopicName = "Projects",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("7cbf4bb9-a725-47ad-9157-ff8ed1eca61d"),
                            ParentTopicId = new Guid("262f36ed-c72b-4ca3-a959-acefc2bcd524"),
                            TopicFullName = "cybersecurity_laws",
                            TopicName = "Laws",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("010a8542-b355-460d-89ba-80b8c8854518"),
                            ParentTopicId = new Guid("262f36ed-c72b-4ca3-a959-acefc2bcd524"),
                            TopicFullName = "cybersecurity_law_regulations",
                            TopicName = "Law regulations",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("850417fa-568b-4dfb-9f6d-5bcaf31643fd"),
                            ParentTopicId = new Guid("d98ad359-1bd9-4a67-878b-cd45ee6c59c9"),
                            TopicFullName = "programming_news",
                            TopicName = "News",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("18ca51dc-c1ba-4873-ae9c-bceafc11641d"),
                            ParentTopicId = new Guid("d98ad359-1bd9-4a67-878b-cd45ee6c59c9"),
                            TopicFullName = "programming_projects",
                            TopicName = "Projects",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("3360ab96-9a1f-4e14-87f5-426ea5c0fcbd"),
                            ParentTopicId = new Guid("ccc0167e-0b76-46a7-a368-46a66da72399"),
                            TopicFullName = "cybersecurity_news_america",
                            TopicName = "America",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("c80e8e24-f445-465e-95ab-f81a2f9ba3f2"),
                            ParentTopicId = new Guid("ccc0167e-0b76-46a7-a368-46a66da72399"),
                            TopicFullName = "cybersecurity_news_asia",
                            TopicName = "Asia",
                            Version = 0
                        },
                        new
                        {
                            TopicId = new Guid("30e9b054-1cf0-4920-a523-e15da64ae223"),
                            ParentTopicId = new Guid("ccc0167e-0b76-46a7-a368-46a66da72399"),
                            TopicFullName = "cybersecurity_news_europe",
                            TopicName = "Europe",
                            Version = 0
                        });
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserArticleReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("ArticleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "ArticleId");

                    b.HasIndex("ArticleId");

                    b.ToTable("UserArticle", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.ToTable("User", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserTopicReadModel", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<Guid>("TopicId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubscriptionTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId", "TopicId");

                    b.HasIndex("TopicId");

                    b.ToTable("UserTopic", "topic-article-service");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentDislikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "ArticleComment")
                        .WithMany("ArticleCommentDislikes")
                        .HasForeignKey("ArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleComment_ArticleCommentDislikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleCommentDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleCommentDislikes");

                    b.Navigation("ArticleComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentLikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "ArticleComment")
                        .WithMany("ArticleCommentLikes")
                        .HasForeignKey("ArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ArticleComment_ArticleCommentLikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleCommentLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleCommentLikes");

                    b.Navigation("ArticleComment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleComments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_Article_ArticleComments");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentArticleCommentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ParentArticleComment_ChildArticleComments");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleComments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_User_ArticleComments");

                    b.Navigation("Article");

                    b.Navigation("Parent");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleDislikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleDislikes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_ArticleDislikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleDislikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleDislikes");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleLikeReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_ArticleLikes");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_User_ArticleLikes");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Topic")
                        .WithMany("Articles")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Articles");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("FK_ParentTopic_ChildTopics");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserArticleReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", "Article")
                        .WithMany("UserArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Article_UserArticles");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("UserArticles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_UserArticles");

                    b.Navigation("Article");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserTopicReadModel", b =>
                {
                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", "Topic")
                        .WithMany("Users")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Topic_Users");

                    b.HasOne("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", "User")
                        .WithMany("Topics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_User_Topics");

                    b.Navigation("Topic");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleCommentReadModel", b =>
                {
                    b.Navigation("ArticleCommentDislikes");

                    b.Navigation("ArticleCommentLikes");

                    b.Navigation("Children");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.ArticleReadModel", b =>
                {
                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleDislikes");

                    b.Navigation("ArticleLikes");

                    b.Navigation("UserArticles");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.TopicReadModel", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("TopicArticleService.Infrastructure.EntityFramework.Models.UserReadModel", b =>
                {
                    b.Navigation("ArticleCommentDislikes");

                    b.Navigation("ArticleCommentLikes");

                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleDislikes");

                    b.Navigation("ArticleLikes");

                    b.Navigation("Topics");

                    b.Navigation("UserArticles");
                });
#pragma warning restore 612, 618
        }
    }
}
